// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package repository

import (
	"context"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (
  id,
  name,
  health_check_path
) VALUES (
  ?, ?, ?
)
RETURNING id, name, health_check_path, created_at, updated_at
`

type CreateAppParams struct {
	ID              string
	Name            string
	HealthCheckPath string
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.queryRow(ctx, q.createAppStmt, createApp, arg.ID, arg.Name, arg.HealthCheckPath)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HealthCheckPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps
WHERE id = ?
`

func (q *Queries) DeleteApp(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteAppStmt, deleteApp, id)
	return err
}

const getApp = `-- name: GetApp :one
SELECT id, name, health_check_path, created_at, updated_at FROM apps
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetApp(ctx context.Context, id string) (App, error) {
	row := q.queryRow(ctx, q.getAppStmt, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HealthCheckPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppByName = `-- name: GetAppByName :one
SELECT id, name, health_check_path, created_at, updated_at FROM apps
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetAppByName(ctx context.Context, name string) (App, error) {
	row := q.queryRow(ctx, q.getAppByNameStmt, getAppByName, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HealthCheckPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT id, name, health_check_path, created_at, updated_at FROM apps
ORDER BY created_at DESC
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.query(ctx, q.listAppsStmt, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HealthCheckPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :exec
UPDATE apps
SET
  name = ?,
  health_check_path = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAppParams struct {
	Name            string
	HealthCheckPath string
	ID              string
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) error {
	_, err := q.exec(ctx, q.updateAppStmt, updateApp, arg.Name, arg.HealthCheckPath, arg.ID)
	return err
}
