// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAppStmt, err = db.PrepareContext(ctx, createApp); err != nil {
		return nil, fmt.Errorf("error preparing query CreateApp: %w", err)
	}
	if q.createDeploymentStmt, err = db.PrepareContext(ctx, createDeployment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDeployment: %w", err)
	}
	if q.createDeploymentLogStmt, err = db.PrepareContext(ctx, createDeploymentLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDeploymentLog: %w", err)
	}
	if q.createDomainStmt, err = db.PrepareContext(ctx, createDomain); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDomain: %w", err)
	}
	if q.deleteAppStmt, err = db.PrepareContext(ctx, deleteApp); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteApp: %w", err)
	}
	if q.deleteDeploymentStmt, err = db.PrepareContext(ctx, deleteDeployment); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDeployment: %w", err)
	}
	if q.deleteDeploymentLogsStmt, err = db.PrepareContext(ctx, deleteDeploymentLogs); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDeploymentLogs: %w", err)
	}
	if q.deleteDomainStmt, err = db.PrepareContext(ctx, deleteDomain); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDomain: %w", err)
	}
	if q.getActiveDeploymentByAppStmt, err = db.PrepareContext(ctx, getActiveDeploymentByApp); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveDeploymentByApp: %w", err)
	}
	if q.getActiveDomainsStmt, err = db.PrepareContext(ctx, getActiveDomains); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveDomains: %w", err)
	}
	if q.getAppStmt, err = db.PrepareContext(ctx, getApp); err != nil {
		return nil, fmt.Errorf("error preparing query GetApp: %w", err)
	}
	if q.getAppByNameStmt, err = db.PrepareContext(ctx, getAppByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetAppByName: %w", err)
	}
	if q.getDeploymentStmt, err = db.PrepareContext(ctx, getDeployment); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeployment: %w", err)
	}
	if q.getDeploymentLogsStmt, err = db.PrepareContext(ctx, getDeploymentLogs); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeploymentLogs: %w", err)
	}
	if q.getDeploymentsByAppAndStatusesStmt, err = db.PrepareContext(ctx, getDeploymentsByAppAndStatuses); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeploymentsByAppAndStatuses: %w", err)
	}
	if q.getDeploymentsNeedingWorkStmt, err = db.PrepareContext(ctx, getDeploymentsNeedingWork); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeploymentsNeedingWork: %w", err)
	}
	if q.getDomainStmt, err = db.PrepareContext(ctx, getDomain); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomain: %w", err)
	}
	if q.getDomainByNameStmt, err = db.PrepareContext(ctx, getDomainByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomainByName: %w", err)
	}
	if q.getRecentDeploymentLogsStmt, err = db.PrepareContext(ctx, getRecentDeploymentLogs); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentDeploymentLogs: %w", err)
	}
	if q.getStaleDeploymentsStmt, err = db.PrepareContext(ctx, getStaleDeployments); err != nil {
		return nil, fmt.Errorf("error preparing query GetStaleDeployments: %w", err)
	}
	if q.listAllDomainsStmt, err = db.PrepareContext(ctx, listAllDomains); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllDomains: %w", err)
	}
	if q.listAppsStmt, err = db.PrepareContext(ctx, listApps); err != nil {
		return nil, fmt.Errorf("error preparing query ListApps: %w", err)
	}
	if q.listDeploymentsByAppStmt, err = db.PrepareContext(ctx, listDeploymentsByApp); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeploymentsByApp: %w", err)
	}
	if q.listDeploymentsByStatusStmt, err = db.PrepareContext(ctx, listDeploymentsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeploymentsByStatus: %w", err)
	}
	if q.listDomainsByAppStmt, err = db.PrepareContext(ctx, listDomainsByApp); err != nil {
		return nil, fmt.Errorf("error preparing query ListDomainsByApp: %w", err)
	}
	if q.updateAppStmt, err = db.PrepareContext(ctx, updateApp); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateApp: %w", err)
	}
	if q.updateDeploymentStatusStmt, err = db.PrepareContext(ctx, updateDeploymentStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDeploymentStatus: %w", err)
	}
	if q.updateDeploymentStatusWithActivatedAtStmt, err = db.PrepareContext(ctx, updateDeploymentStatusWithActivatedAt); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDeploymentStatusWithActivatedAt: %w", err)
	}
	if q.updateDeploymentStatusWithStoppedAtStmt, err = db.PrepareContext(ctx, updateDeploymentStatusWithStoppedAt); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDeploymentStatusWithStoppedAt: %w", err)
	}
	if q.updateDomainStmt, err = db.PrepareContext(ctx, updateDomain); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDomain: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAppStmt != nil {
		if cerr := q.createAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAppStmt: %w", cerr)
		}
	}
	if q.createDeploymentStmt != nil {
		if cerr := q.createDeploymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeploymentStmt: %w", cerr)
		}
	}
	if q.createDeploymentLogStmt != nil {
		if cerr := q.createDeploymentLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeploymentLogStmt: %w", cerr)
		}
	}
	if q.createDomainStmt != nil {
		if cerr := q.createDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDomainStmt: %w", cerr)
		}
	}
	if q.deleteAppStmt != nil {
		if cerr := q.deleteAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAppStmt: %w", cerr)
		}
	}
	if q.deleteDeploymentStmt != nil {
		if cerr := q.deleteDeploymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDeploymentStmt: %w", cerr)
		}
	}
	if q.deleteDeploymentLogsStmt != nil {
		if cerr := q.deleteDeploymentLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDeploymentLogsStmt: %w", cerr)
		}
	}
	if q.deleteDomainStmt != nil {
		if cerr := q.deleteDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDomainStmt: %w", cerr)
		}
	}
	if q.getActiveDeploymentByAppStmt != nil {
		if cerr := q.getActiveDeploymentByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveDeploymentByAppStmt: %w", cerr)
		}
	}
	if q.getActiveDomainsStmt != nil {
		if cerr := q.getActiveDomainsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveDomainsStmt: %w", cerr)
		}
	}
	if q.getAppStmt != nil {
		if cerr := q.getAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAppStmt: %w", cerr)
		}
	}
	if q.getAppByNameStmt != nil {
		if cerr := q.getAppByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAppByNameStmt: %w", cerr)
		}
	}
	if q.getDeploymentStmt != nil {
		if cerr := q.getDeploymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeploymentStmt: %w", cerr)
		}
	}
	if q.getDeploymentLogsStmt != nil {
		if cerr := q.getDeploymentLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeploymentLogsStmt: %w", cerr)
		}
	}
	if q.getDeploymentsByAppAndStatusesStmt != nil {
		if cerr := q.getDeploymentsByAppAndStatusesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeploymentsByAppAndStatusesStmt: %w", cerr)
		}
	}
	if q.getDeploymentsNeedingWorkStmt != nil {
		if cerr := q.getDeploymentsNeedingWorkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeploymentsNeedingWorkStmt: %w", cerr)
		}
	}
	if q.getDomainStmt != nil {
		if cerr := q.getDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainStmt: %w", cerr)
		}
	}
	if q.getDomainByNameStmt != nil {
		if cerr := q.getDomainByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainByNameStmt: %w", cerr)
		}
	}
	if q.getRecentDeploymentLogsStmt != nil {
		if cerr := q.getRecentDeploymentLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentDeploymentLogsStmt: %w", cerr)
		}
	}
	if q.getStaleDeploymentsStmt != nil {
		if cerr := q.getStaleDeploymentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStaleDeploymentsStmt: %w", cerr)
		}
	}
	if q.listAllDomainsStmt != nil {
		if cerr := q.listAllDomainsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllDomainsStmt: %w", cerr)
		}
	}
	if q.listAppsStmt != nil {
		if cerr := q.listAppsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAppsStmt: %w", cerr)
		}
	}
	if q.listDeploymentsByAppStmt != nil {
		if cerr := q.listDeploymentsByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeploymentsByAppStmt: %w", cerr)
		}
	}
	if q.listDeploymentsByStatusStmt != nil {
		if cerr := q.listDeploymentsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeploymentsByStatusStmt: %w", cerr)
		}
	}
	if q.listDomainsByAppStmt != nil {
		if cerr := q.listDomainsByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDomainsByAppStmt: %w", cerr)
		}
	}
	if q.updateAppStmt != nil {
		if cerr := q.updateAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAppStmt: %w", cerr)
		}
	}
	if q.updateDeploymentStatusStmt != nil {
		if cerr := q.updateDeploymentStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDeploymentStatusStmt: %w", cerr)
		}
	}
	if q.updateDeploymentStatusWithActivatedAtStmt != nil {
		if cerr := q.updateDeploymentStatusWithActivatedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDeploymentStatusWithActivatedAtStmt: %w", cerr)
		}
	}
	if q.updateDeploymentStatusWithStoppedAtStmt != nil {
		if cerr := q.updateDeploymentStatusWithStoppedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDeploymentStatusWithStoppedAtStmt: %w", cerr)
		}
	}
	if q.updateDomainStmt != nil {
		if cerr := q.updateDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDomainStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                        DBTX
	tx                                        *sql.Tx
	createAppStmt                             *sql.Stmt
	createDeploymentStmt                      *sql.Stmt
	createDeploymentLogStmt                   *sql.Stmt
	createDomainStmt                          *sql.Stmt
	deleteAppStmt                             *sql.Stmt
	deleteDeploymentStmt                      *sql.Stmt
	deleteDeploymentLogsStmt                  *sql.Stmt
	deleteDomainStmt                          *sql.Stmt
	getActiveDeploymentByAppStmt              *sql.Stmt
	getActiveDomainsStmt                      *sql.Stmt
	getAppStmt                                *sql.Stmt
	getAppByNameStmt                          *sql.Stmt
	getDeploymentStmt                         *sql.Stmt
	getDeploymentLogsStmt                     *sql.Stmt
	getDeploymentsByAppAndStatusesStmt        *sql.Stmt
	getDeploymentsNeedingWorkStmt             *sql.Stmt
	getDomainStmt                             *sql.Stmt
	getDomainByNameStmt                       *sql.Stmt
	getRecentDeploymentLogsStmt               *sql.Stmt
	getStaleDeploymentsStmt                   *sql.Stmt
	listAllDomainsStmt                        *sql.Stmt
	listAppsStmt                              *sql.Stmt
	listDeploymentsByAppStmt                  *sql.Stmt
	listDeploymentsByStatusStmt               *sql.Stmt
	listDomainsByAppStmt                      *sql.Stmt
	updateAppStmt                             *sql.Stmt
	updateDeploymentStatusStmt                *sql.Stmt
	updateDeploymentStatusWithActivatedAtStmt *sql.Stmt
	updateDeploymentStatusWithStoppedAtStmt   *sql.Stmt
	updateDomainStmt                          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                        tx,
		tx:                                        tx,
		createAppStmt:                             q.createAppStmt,
		createDeploymentStmt:                      q.createDeploymentStmt,
		createDeploymentLogStmt:                   q.createDeploymentLogStmt,
		createDomainStmt:                          q.createDomainStmt,
		deleteAppStmt:                             q.deleteAppStmt,
		deleteDeploymentStmt:                      q.deleteDeploymentStmt,
		deleteDeploymentLogsStmt:                  q.deleteDeploymentLogsStmt,
		deleteDomainStmt:                          q.deleteDomainStmt,
		getActiveDeploymentByAppStmt:              q.getActiveDeploymentByAppStmt,
		getActiveDomainsStmt:                      q.getActiveDomainsStmt,
		getAppStmt:                                q.getAppStmt,
		getAppByNameStmt:                          q.getAppByNameStmt,
		getDeploymentStmt:                         q.getDeploymentStmt,
		getDeploymentLogsStmt:                     q.getDeploymentLogsStmt,
		getDeploymentsByAppAndStatusesStmt:        q.getDeploymentsByAppAndStatusesStmt,
		getDeploymentsNeedingWorkStmt:             q.getDeploymentsNeedingWorkStmt,
		getDomainStmt:                             q.getDomainStmt,
		getDomainByNameStmt:                       q.getDomainByNameStmt,
		getRecentDeploymentLogsStmt:               q.getRecentDeploymentLogsStmt,
		getStaleDeploymentsStmt:                   q.getStaleDeploymentsStmt,
		listAllDomainsStmt:                        q.listAllDomainsStmt,
		listAppsStmt:                              q.listAppsStmt,
		listDeploymentsByAppStmt:                  q.listDeploymentsByAppStmt,
		listDeploymentsByStatusStmt:               q.listDeploymentsByStatusStmt,
		listDomainsByAppStmt:                      q.listDomainsByAppStmt,
		updateAppStmt:                             q.updateAppStmt,
		updateDeploymentStatusStmt:                q.updateDeploymentStatusStmt,
		updateDeploymentStatusWithActivatedAtStmt: q.updateDeploymentStatusWithActivatedAtStmt,
		updateDeploymentStatusWithStoppedAtStmt:   q.updateDeploymentStatusWithStoppedAtStmt,
		updateDomainStmt:                          q.updateDomainStmt,
	}
}
