// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package repository

import (
	"context"
	"strings"
	"time"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
  id,
  app_id,
  commit_hash,
  port,
  host,
  status
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, app_id, commit_hash, port, host, status, created_at, activated_at, stopped_at
`

type CreateDeploymentParams struct {
	ID         string
	AppID      string
	CommitHash string
	Port       int64
	Host       string
	Status     string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.queryRow(ctx, q.createDeploymentStmt, createDeployment,
		arg.ID,
		arg.AppID,
		arg.CommitHash,
		arg.Port,
		arg.Host,
		arg.Status,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.CommitHash,
		&i.Port,
		&i.Host,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.StoppedAt,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments
WHERE id = ?
`

func (q *Queries) DeleteDeployment(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteDeploymentStmt, deleteDeployment, id)
	return err
}

const getActiveDeploymentByApp = `-- name: GetActiveDeploymentByApp :one
SELECT id, app_id, commit_hash, port, host, status, created_at, activated_at, stopped_at FROM deployments
WHERE app_id = ? AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveDeploymentByApp(ctx context.Context, appID string) (Deployment, error) {
	row := q.queryRow(ctx, q.getActiveDeploymentByAppStmt, getActiveDeploymentByApp, appID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.CommitHash,
		&i.Port,
		&i.Host,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.StoppedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, app_id, commit_hash, port, host, status, created_at, activated_at, stopped_at FROM deployments
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.queryRow(ctx, q.getDeploymentStmt, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.CommitHash,
		&i.Port,
		&i.Host,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.StoppedAt,
	)
	return i, err
}

const getDeploymentsByAppAndStatuses = `-- name: GetDeploymentsByAppAndStatuses :many
SELECT id, app_id, commit_hash, port, host, status, created_at, activated_at, stopped_at FROM deployments
WHERE app_id = ? AND status IN (/*SLICE:statuses*/?)
ORDER BY created_at DESC
`

type GetDeploymentsByAppAndStatusesParams struct {
	AppID    string
	Statuses []string
}

func (q *Queries) GetDeploymentsByAppAndStatuses(ctx context.Context, arg GetDeploymentsByAppAndStatusesParams) ([]Deployment, error) {
	query := getDeploymentsByAppAndStatuses
	var queryParams []interface{}
	queryParams = append(queryParams, arg.AppID)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CommitHash,
			&i.Port,
			&i.Host,
			&i.Status,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentsNeedingWork = `-- name: GetDeploymentsNeedingWork :many
SELECT id, app_id, commit_hash, port, host, status, created_at, activated_at, stopped_at FROM deployments
WHERE status IN (
  'pending',
  'building',
  'starting',
  'health_checking',
  'ready',
  'activating',
  'cancelling'
)
ORDER BY created_at ASC
`

func (q *Queries) GetDeploymentsNeedingWork(ctx context.Context) ([]Deployment, error) {
	rows, err := q.query(ctx, q.getDeploymentsNeedingWorkStmt, getDeploymentsNeedingWork)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CommitHash,
			&i.Port,
			&i.Host,
			&i.Status,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleDeployments = `-- name: GetStaleDeployments :many
SELECT id, app_id, commit_hash, port, host, status, created_at, activated_at, stopped_at FROM deployments
WHERE status IN (
  'building',
  'starting',
  'health_checking',
  'activating'
)
AND created_at < ?
ORDER BY created_at ASC
`

func (q *Queries) GetStaleDeployments(ctx context.Context, createdAt time.Time) ([]Deployment, error) {
	rows, err := q.query(ctx, q.getStaleDeploymentsStmt, getStaleDeployments, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CommitHash,
			&i.Port,
			&i.Host,
			&i.Status,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
SELECT id, app_id, commit_hash, port, host, status, created_at, activated_at, stopped_at FROM deployments
WHERE app_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByApp(ctx context.Context, appID string) ([]Deployment, error) {
	rows, err := q.query(ctx, q.listDeploymentsByAppStmt, listDeploymentsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CommitHash,
			&i.Port,
			&i.Host,
			&i.Status,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByStatus = `-- name: ListDeploymentsByStatus :many
SELECT id, app_id, commit_hash, port, host, status, created_at, activated_at, stopped_at FROM deployments
WHERE status = ?
ORDER BY created_at ASC
`

func (q *Queries) ListDeploymentsByStatus(ctx context.Context, status string) ([]Deployment, error) {
	rows, err := q.query(ctx, q.listDeploymentsByStatusStmt, listDeploymentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CommitHash,
			&i.Port,
			&i.Host,
			&i.Status,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.exec(ctx, q.updateDeploymentStatusStmt, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}

const updateDeploymentStatusWithActivatedAt = `-- name: UpdateDeploymentStatusWithActivatedAt :exec
UPDATE deployments
SET
  status = ?,
  activated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDeploymentStatusWithActivatedAtParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateDeploymentStatusWithActivatedAt(ctx context.Context, arg UpdateDeploymentStatusWithActivatedAtParams) error {
	_, err := q.exec(ctx, q.updateDeploymentStatusWithActivatedAtStmt, updateDeploymentStatusWithActivatedAt, arg.Status, arg.ID)
	return err
}

const updateDeploymentStatusWithStoppedAt = `-- name: UpdateDeploymentStatusWithStoppedAt :exec
UPDATE deployments
SET
  status = ?,
  stopped_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDeploymentStatusWithStoppedAtParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateDeploymentStatusWithStoppedAt(ctx context.Context, arg UpdateDeploymentStatusWithStoppedAtParams) error {
	_, err := q.exec(ctx, q.updateDeploymentStatusWithStoppedAtStmt, updateDeploymentStatusWithStoppedAt, arg.Status, arg.ID)
	return err
}
