// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_logs.sql

package repository

import (
	"context"
)

const createDeploymentLog = `-- name: CreateDeploymentLog :exec
INSERT INTO deployment_logs (
  id,
  deployment_id,
  event,
  message,
  error
) VALUES (
  ?, ?, ?, ?, ?
)
`

type CreateDeploymentLogParams struct {
	ID           string
	DeploymentID string
	Event        string
	Message      *string
	Error        *string
}

func (q *Queries) CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) error {
	_, err := q.exec(ctx, q.createDeploymentLogStmt, createDeploymentLog,
		arg.ID,
		arg.DeploymentID,
		arg.Event,
		arg.Message,
		arg.Error,
	)
	return err
}

const deleteDeploymentLogs = `-- name: DeleteDeploymentLogs :exec
DELETE FROM deployment_logs
WHERE deployment_id = ?
`

func (q *Queries) DeleteDeploymentLogs(ctx context.Context, deploymentID string) error {
	_, err := q.exec(ctx, q.deleteDeploymentLogsStmt, deleteDeploymentLogs, deploymentID)
	return err
}

const getDeploymentLogs = `-- name: GetDeploymentLogs :many
SELECT id, deployment_id, event, message, error, created_at FROM deployment_logs
WHERE deployment_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetDeploymentLogs(ctx context.Context, deploymentID string) ([]DeploymentLog, error) {
	rows, err := q.query(ctx, q.getDeploymentLogsStmt, getDeploymentLogs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Event,
			&i.Message,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentDeploymentLogs = `-- name: GetRecentDeploymentLogs :many
SELECT id, deployment_id, event, message, error, created_at FROM deployment_logs
WHERE deployment_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetRecentDeploymentLogsParams struct {
	DeploymentID string
	Limit        int64
}

func (q *Queries) GetRecentDeploymentLogs(ctx context.Context, arg GetRecentDeploymentLogsParams) ([]DeploymentLog, error) {
	rows, err := q.query(ctx, q.getRecentDeploymentLogsStmt, getRecentDeploymentLogs, arg.DeploymentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Event,
			&i.Message,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
