// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package repository

import (
	"context"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (
  id,
  domain,
  app_id,
  tls_enabled
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, domain, app_id, tls_enabled, created_at
`

type CreateDomainParams struct {
	ID         string
	Domain     string
	AppID      string
	TlsEnabled bool
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.queryRow(ctx, q.createDomainStmt, createDomain,
		arg.ID,
		arg.Domain,
		arg.AppID,
		arg.TlsEnabled,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.AppID,
		&i.TlsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains
WHERE id = ?
`

func (q *Queries) DeleteDomain(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteDomainStmt, deleteDomain, id)
	return err
}

const getActiveDomains = `-- name: GetActiveDomains :many
SELECT
  d.id,
  d.domain,
  d.app_id,
  d.tls_enabled,
  d.created_at
FROM domains d
INNER JOIN deployments dep ON dep.app_id = d.app_id
WHERE dep.status = 'active'
`

func (q *Queries) GetActiveDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.query(ctx, q.getActiveDomainsStmt, getActiveDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.AppID,
			&i.TlsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomain = `-- name: GetDomain :one
SELECT id, domain, app_id, tls_enabled, created_at FROM domains
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.queryRow(ctx, q.getDomainStmt, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.AppID,
		&i.TlsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, domain, app_id, tls_enabled, created_at FROM domains
WHERE domain = ?
LIMIT 1
`

func (q *Queries) GetDomainByName(ctx context.Context, domain string) (Domain, error) {
	row := q.queryRow(ctx, q.getDomainByNameStmt, getDomainByName, domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.AppID,
		&i.TlsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const listAllDomains = `-- name: ListAllDomains :many
SELECT id, domain, app_id, tls_enabled, created_at FROM domains
ORDER BY created_at DESC
`

func (q *Queries) ListAllDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.query(ctx, q.listAllDomainsStmt, listAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.AppID,
			&i.TlsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByApp = `-- name: ListDomainsByApp :many
SELECT id, domain, app_id, tls_enabled, created_at FROM domains
WHERE app_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListDomainsByApp(ctx context.Context, appID string) ([]Domain, error) {
	rows, err := q.query(ctx, q.listDomainsByAppStmt, listDomainsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.AppID,
			&i.TlsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomain = `-- name: UpdateDomain :exec
UPDATE domains
SET
  domain = ?,
  tls_enabled = ?
WHERE id = ?
`

type UpdateDomainParams struct {
	Domain     string
	TlsEnabled bool
	ID         string
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) error {
	_, err := q.exec(ctx, q.updateDomainStmt, updateDomain, arg.Domain, arg.TlsEnabled, arg.ID)
	return err
}
