// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"
)

type App struct {
	ID              string
	Name            string
	HealthCheckPath string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Deployment struct {
	ID          string
	AppID       string
	CommitHash  string
	Port        int64
	Host        string
	Status      string
	CreatedAt   time.Time
	ActivatedAt *time.Time
	StoppedAt   *time.Time
}

type DeploymentLog struct {
	ID           string
	DeploymentID string
	Event        string
	Message      *string
	Error        *string
	CreatedAt    time.Time
}

type Domain struct {
	ID         string
	Domain     string
	AppID      string
	TlsEnabled bool
	CreatedAt  time.Time
}
