// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"time"
)

type Querier interface {
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) error
	CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error)
	DeleteApp(ctx context.Context, id string) error
	DeleteDeployment(ctx context.Context, id string) error
	DeleteDeploymentLogs(ctx context.Context, deploymentID string) error
	DeleteDomain(ctx context.Context, id string) error
	GetActiveDeploymentByApp(ctx context.Context, appID string) (Deployment, error)
	GetActiveDomains(ctx context.Context) ([]Domain, error)
	GetApp(ctx context.Context, id string) (App, error)
	GetAppByName(ctx context.Context, name string) (App, error)
	GetDeployment(ctx context.Context, id string) (Deployment, error)
	GetDeploymentLogs(ctx context.Context, deploymentID string) ([]DeploymentLog, error)
	GetDeploymentsByAppAndStatuses(ctx context.Context, arg GetDeploymentsByAppAndStatusesParams) ([]Deployment, error)
	GetDeploymentsNeedingWork(ctx context.Context) ([]Deployment, error)
	GetDomain(ctx context.Context, id string) (Domain, error)
	GetDomainByName(ctx context.Context, domain string) (Domain, error)
	GetRecentDeploymentLogs(ctx context.Context, arg GetRecentDeploymentLogsParams) ([]DeploymentLog, error)
	GetStaleDeployments(ctx context.Context, createdAt time.Time) ([]Deployment, error)
	ListAllDomains(ctx context.Context) ([]Domain, error)
	ListApps(ctx context.Context) ([]App, error)
	ListDeploymentsByApp(ctx context.Context, appID string) ([]Deployment, error)
	ListDeploymentsByStatus(ctx context.Context, status string) ([]Deployment, error)
	ListDomainsByApp(ctx context.Context, appID string) ([]Domain, error)
	UpdateApp(ctx context.Context, arg UpdateAppParams) error
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error
	UpdateDeploymentStatusWithActivatedAt(ctx context.Context, arg UpdateDeploymentStatusWithActivatedAtParams) error
	UpdateDeploymentStatusWithStoppedAt(ctx context.Context, arg UpdateDeploymentStatusWithStoppedAtParams) error
	UpdateDomain(ctx context.Context, arg UpdateDomainParams) error
}

var _ Querier = (*Queries)(nil)
