// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/dmitrymomot/runlite/db/repository"
)

// NewQueries creates a new instance of Queries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *Queries {
	mock := &Queries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Queries is an autogenerated mock type for the Querier type
type Queries struct {
	mock.Mock
}

type Queries_Expecter struct {
	mock *mock.Mock
}

func (_m *Queries) EXPECT() *Queries_Expecter {
	return &Queries_Expecter{mock: &_m.Mock}
}

// CreateApp provides a mock function for the type Queries
func (_mock *Queries) CreateApp(ctx context.Context, arg repository.CreateAppParams) (repository.App, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateApp")
	}

	var r0 repository.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateAppParams) (repository.App, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateAppParams) repository.App); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.App)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CreateAppParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_CreateApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApp'
type Queries_CreateApp_Call struct {
	*mock.Call
}

// CreateApp is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.CreateAppParams
func (_e *Queries_Expecter) CreateApp(ctx interface{}, arg interface{}) *Queries_CreateApp_Call {
	return &Queries_CreateApp_Call{Call: _e.mock.On("CreateApp", ctx, arg)}
}

func (_c *Queries_CreateApp_Call) Run(run func(ctx context.Context, arg repository.CreateAppParams)) *Queries_CreateApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreateAppParams
		if args[1] != nil {
			arg1 = args[1].(repository.CreateAppParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_CreateApp_Call) Return(app repository.App, err error) *Queries_CreateApp_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *Queries_CreateApp_Call) RunAndReturn(run func(ctx context.Context, arg repository.CreateAppParams) (repository.App, error)) *Queries_CreateApp_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDeployment provides a mock function for the type Queries
func (_mock *Queries) CreateDeployment(ctx context.Context, arg repository.CreateDeploymentParams) (repository.Deployment, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeployment")
	}

	var r0 repository.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateDeploymentParams) (repository.Deployment, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateDeploymentParams) repository.Deployment); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Deployment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CreateDeploymentParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_CreateDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeployment'
type Queries_CreateDeployment_Call struct {
	*mock.Call
}

// CreateDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.CreateDeploymentParams
func (_e *Queries_Expecter) CreateDeployment(ctx interface{}, arg interface{}) *Queries_CreateDeployment_Call {
	return &Queries_CreateDeployment_Call{Call: _e.mock.On("CreateDeployment", ctx, arg)}
}

func (_c *Queries_CreateDeployment_Call) Run(run func(ctx context.Context, arg repository.CreateDeploymentParams)) *Queries_CreateDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreateDeploymentParams
		if args[1] != nil {
			arg1 = args[1].(repository.CreateDeploymentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_CreateDeployment_Call) Return(deployment repository.Deployment, err error) *Queries_CreateDeployment_Call {
	_c.Call.Return(deployment, err)
	return _c
}

func (_c *Queries_CreateDeployment_Call) RunAndReturn(run func(ctx context.Context, arg repository.CreateDeploymentParams) (repository.Deployment, error)) *Queries_CreateDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDeploymentLog provides a mock function for the type Queries
func (_mock *Queries) CreateDeploymentLog(ctx context.Context, arg repository.CreateDeploymentLogParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeploymentLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateDeploymentLogParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_CreateDeploymentLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeploymentLog'
type Queries_CreateDeploymentLog_Call struct {
	*mock.Call
}

// CreateDeploymentLog is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.CreateDeploymentLogParams
func (_e *Queries_Expecter) CreateDeploymentLog(ctx interface{}, arg interface{}) *Queries_CreateDeploymentLog_Call {
	return &Queries_CreateDeploymentLog_Call{Call: _e.mock.On("CreateDeploymentLog", ctx, arg)}
}

func (_c *Queries_CreateDeploymentLog_Call) Run(run func(ctx context.Context, arg repository.CreateDeploymentLogParams)) *Queries_CreateDeploymentLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreateDeploymentLogParams
		if args[1] != nil {
			arg1 = args[1].(repository.CreateDeploymentLogParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_CreateDeploymentLog_Call) Return(err error) *Queries_CreateDeploymentLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_CreateDeploymentLog_Call) RunAndReturn(run func(ctx context.Context, arg repository.CreateDeploymentLogParams) error) *Queries_CreateDeploymentLog_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDomain provides a mock function for the type Queries
func (_mock *Queries) CreateDomain(ctx context.Context, arg repository.CreateDomainParams) (repository.Domain, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDomain")
	}

	var r0 repository.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateDomainParams) (repository.Domain, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateDomainParams) repository.Domain); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Domain)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CreateDomainParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_CreateDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDomain'
type Queries_CreateDomain_Call struct {
	*mock.Call
}

// CreateDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.CreateDomainParams
func (_e *Queries_Expecter) CreateDomain(ctx interface{}, arg interface{}) *Queries_CreateDomain_Call {
	return &Queries_CreateDomain_Call{Call: _e.mock.On("CreateDomain", ctx, arg)}
}

func (_c *Queries_CreateDomain_Call) Run(run func(ctx context.Context, arg repository.CreateDomainParams)) *Queries_CreateDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreateDomainParams
		if args[1] != nil {
			arg1 = args[1].(repository.CreateDomainParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_CreateDomain_Call) Return(domain repository.Domain, err error) *Queries_CreateDomain_Call {
	_c.Call.Return(domain, err)
	return _c
}

func (_c *Queries_CreateDomain_Call) RunAndReturn(run func(ctx context.Context, arg repository.CreateDomainParams) (repository.Domain, error)) *Queries_CreateDomain_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApp provides a mock function for the type Queries
func (_mock *Queries) DeleteApp(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_DeleteApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApp'
type Queries_DeleteApp_Call struct {
	*mock.Call
}

// DeleteApp is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Queries_Expecter) DeleteApp(ctx interface{}, id interface{}) *Queries_DeleteApp_Call {
	return &Queries_DeleteApp_Call{Call: _e.mock.On("DeleteApp", ctx, id)}
}

func (_c *Queries_DeleteApp_Call) Run(run func(ctx context.Context, id string)) *Queries_DeleteApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_DeleteApp_Call) Return(err error) *Queries_DeleteApp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_DeleteApp_Call) RunAndReturn(run func(ctx context.Context, id string) error) *Queries_DeleteApp_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDeployment provides a mock function for the type Queries
func (_mock *Queries) DeleteDeployment(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeployment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_DeleteDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeployment'
type Queries_DeleteDeployment_Call struct {
	*mock.Call
}

// DeleteDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Queries_Expecter) DeleteDeployment(ctx interface{}, id interface{}) *Queries_DeleteDeployment_Call {
	return &Queries_DeleteDeployment_Call{Call: _e.mock.On("DeleteDeployment", ctx, id)}
}

func (_c *Queries_DeleteDeployment_Call) Run(run func(ctx context.Context, id string)) *Queries_DeleteDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_DeleteDeployment_Call) Return(err error) *Queries_DeleteDeployment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_DeleteDeployment_Call) RunAndReturn(run func(ctx context.Context, id string) error) *Queries_DeleteDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDeploymentLogs provides a mock function for the type Queries
func (_mock *Queries) DeleteDeploymentLogs(ctx context.Context, deploymentID string) error {
	ret := _mock.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeploymentLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, deploymentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_DeleteDeploymentLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeploymentLogs'
type Queries_DeleteDeploymentLogs_Call struct {
	*mock.Call
}

// DeleteDeploymentLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
func (_e *Queries_Expecter) DeleteDeploymentLogs(ctx interface{}, deploymentID interface{}) *Queries_DeleteDeploymentLogs_Call {
	return &Queries_DeleteDeploymentLogs_Call{Call: _e.mock.On("DeleteDeploymentLogs", ctx, deploymentID)}
}

func (_c *Queries_DeleteDeploymentLogs_Call) Run(run func(ctx context.Context, deploymentID string)) *Queries_DeleteDeploymentLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_DeleteDeploymentLogs_Call) Return(err error) *Queries_DeleteDeploymentLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_DeleteDeploymentLogs_Call) RunAndReturn(run func(ctx context.Context, deploymentID string) error) *Queries_DeleteDeploymentLogs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDomain provides a mock function for the type Queries
func (_mock *Queries) DeleteDomain(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_DeleteDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDomain'
type Queries_DeleteDomain_Call struct {
	*mock.Call
}

// DeleteDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Queries_Expecter) DeleteDomain(ctx interface{}, id interface{}) *Queries_DeleteDomain_Call {
	return &Queries_DeleteDomain_Call{Call: _e.mock.On("DeleteDomain", ctx, id)}
}

func (_c *Queries_DeleteDomain_Call) Run(run func(ctx context.Context, id string)) *Queries_DeleteDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_DeleteDomain_Call) Return(err error) *Queries_DeleteDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_DeleteDomain_Call) RunAndReturn(run func(ctx context.Context, id string) error) *Queries_DeleteDomain_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveDeploymentByApp provides a mock function for the type Queries
func (_mock *Queries) GetActiveDeploymentByApp(ctx context.Context, appID string) (repository.Deployment, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveDeploymentByApp")
	}

	var r0 repository.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.Deployment, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.Deployment); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		r0 = ret.Get(0).(repository.Deployment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetActiveDeploymentByApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveDeploymentByApp'
type Queries_GetActiveDeploymentByApp_Call struct {
	*mock.Call
}

// GetActiveDeploymentByApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *Queries_Expecter) GetActiveDeploymentByApp(ctx interface{}, appID interface{}) *Queries_GetActiveDeploymentByApp_Call {
	return &Queries_GetActiveDeploymentByApp_Call{Call: _e.mock.On("GetActiveDeploymentByApp", ctx, appID)}
}

func (_c *Queries_GetActiveDeploymentByApp_Call) Run(run func(ctx context.Context, appID string)) *Queries_GetActiveDeploymentByApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetActiveDeploymentByApp_Call) Return(deployment repository.Deployment, err error) *Queries_GetActiveDeploymentByApp_Call {
	_c.Call.Return(deployment, err)
	return _c
}

func (_c *Queries_GetActiveDeploymentByApp_Call) RunAndReturn(run func(ctx context.Context, appID string) (repository.Deployment, error)) *Queries_GetActiveDeploymentByApp_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveDomains provides a mock function for the type Queries
func (_mock *Queries) GetActiveDomains(ctx context.Context) ([]repository.Domain, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveDomains")
	}

	var r0 []repository.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repository.Domain, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repository.Domain); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Domain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetActiveDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveDomains'
type Queries_GetActiveDomains_Call struct {
	*mock.Call
}

// GetActiveDomains is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queries_Expecter) GetActiveDomains(ctx interface{}) *Queries_GetActiveDomains_Call {
	return &Queries_GetActiveDomains_Call{Call: _e.mock.On("GetActiveDomains", ctx)}
}

func (_c *Queries_GetActiveDomains_Call) Run(run func(ctx context.Context)) *Queries_GetActiveDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queries_GetActiveDomains_Call) Return(domains []repository.Domain, err error) *Queries_GetActiveDomains_Call {
	_c.Call.Return(domains, err)
	return _c
}

func (_c *Queries_GetActiveDomains_Call) RunAndReturn(run func(ctx context.Context) ([]repository.Domain, error)) *Queries_GetActiveDomains_Call {
	_c.Call.Return(run)
	return _c
}

// GetApp provides a mock function for the type Queries
func (_mock *Queries) GetApp(ctx context.Context, id string) (repository.App, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetApp")
	}

	var r0 repository.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.App, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.App); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.App)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApp'
type Queries_GetApp_Call struct {
	*mock.Call
}

// GetApp is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Queries_Expecter) GetApp(ctx interface{}, id interface{}) *Queries_GetApp_Call {
	return &Queries_GetApp_Call{Call: _e.mock.On("GetApp", ctx, id)}
}

func (_c *Queries_GetApp_Call) Run(run func(ctx context.Context, id string)) *Queries_GetApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetApp_Call) Return(app repository.App, err error) *Queries_GetApp_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *Queries_GetApp_Call) RunAndReturn(run func(ctx context.Context, id string) (repository.App, error)) *Queries_GetApp_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppByName provides a mock function for the type Queries
func (_mock *Queries) GetAppByName(ctx context.Context, name string) (repository.App, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAppByName")
	}

	var r0 repository.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.App, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.App); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(repository.App)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetAppByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppByName'
type Queries_GetAppByName_Call struct {
	*mock.Call
}

// GetAppByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Queries_Expecter) GetAppByName(ctx interface{}, name interface{}) *Queries_GetAppByName_Call {
	return &Queries_GetAppByName_Call{Call: _e.mock.On("GetAppByName", ctx, name)}
}

func (_c *Queries_GetAppByName_Call) Run(run func(ctx context.Context, name string)) *Queries_GetAppByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetAppByName_Call) Return(app repository.App, err error) *Queries_GetAppByName_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *Queries_GetAppByName_Call) RunAndReturn(run func(ctx context.Context, name string) (repository.App, error)) *Queries_GetAppByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeployment provides a mock function for the type Queries
func (_mock *Queries) GetDeployment(ctx context.Context, id string) (repository.Deployment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDeployment")
	}

	var r0 repository.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.Deployment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.Deployment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Deployment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeployment'
type Queries_GetDeployment_Call struct {
	*mock.Call
}

// GetDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Queries_Expecter) GetDeployment(ctx interface{}, id interface{}) *Queries_GetDeployment_Call {
	return &Queries_GetDeployment_Call{Call: _e.mock.On("GetDeployment", ctx, id)}
}

func (_c *Queries_GetDeployment_Call) Run(run func(ctx context.Context, id string)) *Queries_GetDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetDeployment_Call) Return(deployment repository.Deployment, err error) *Queries_GetDeployment_Call {
	_c.Call.Return(deployment, err)
	return _c
}

func (_c *Queries_GetDeployment_Call) RunAndReturn(run func(ctx context.Context, id string) (repository.Deployment, error)) *Queries_GetDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeploymentLogs provides a mock function for the type Queries
func (_mock *Queries) GetDeploymentLogs(ctx context.Context, deploymentID string) ([]repository.DeploymentLog, error) {
	ret := _mock.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeploymentLogs")
	}

	var r0 []repository.DeploymentLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]repository.DeploymentLog, error)); ok {
		return returnFunc(ctx, deploymentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []repository.DeploymentLog); ok {
		r0 = returnFunc(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DeploymentLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetDeploymentLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeploymentLogs'
type Queries_GetDeploymentLogs_Call struct {
	*mock.Call
}

// GetDeploymentLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
func (_e *Queries_Expecter) GetDeploymentLogs(ctx interface{}, deploymentID interface{}) *Queries_GetDeploymentLogs_Call {
	return &Queries_GetDeploymentLogs_Call{Call: _e.mock.On("GetDeploymentLogs", ctx, deploymentID)}
}

func (_c *Queries_GetDeploymentLogs_Call) Run(run func(ctx context.Context, deploymentID string)) *Queries_GetDeploymentLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetDeploymentLogs_Call) Return(deploymentLogs []repository.DeploymentLog, err error) *Queries_GetDeploymentLogs_Call {
	_c.Call.Return(deploymentLogs, err)
	return _c
}

func (_c *Queries_GetDeploymentLogs_Call) RunAndReturn(run func(ctx context.Context, deploymentID string) ([]repository.DeploymentLog, error)) *Queries_GetDeploymentLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeploymentsByAppAndStatuses provides a mock function for the type Queries
func (_mock *Queries) GetDeploymentsByAppAndStatuses(ctx context.Context, arg repository.GetDeploymentsByAppAndStatusesParams) ([]repository.Deployment, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDeploymentsByAppAndStatuses")
	}

	var r0 []repository.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.GetDeploymentsByAppAndStatusesParams) ([]repository.Deployment, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.GetDeploymentsByAppAndStatusesParams) []repository.Deployment); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.GetDeploymentsByAppAndStatusesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetDeploymentsByAppAndStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeploymentsByAppAndStatuses'
type Queries_GetDeploymentsByAppAndStatuses_Call struct {
	*mock.Call
}

// GetDeploymentsByAppAndStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.GetDeploymentsByAppAndStatusesParams
func (_e *Queries_Expecter) GetDeploymentsByAppAndStatuses(ctx interface{}, arg interface{}) *Queries_GetDeploymentsByAppAndStatuses_Call {
	return &Queries_GetDeploymentsByAppAndStatuses_Call{Call: _e.mock.On("GetDeploymentsByAppAndStatuses", ctx, arg)}
}

func (_c *Queries_GetDeploymentsByAppAndStatuses_Call) Run(run func(ctx context.Context, arg repository.GetDeploymentsByAppAndStatusesParams)) *Queries_GetDeploymentsByAppAndStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.GetDeploymentsByAppAndStatusesParams
		if args[1] != nil {
			arg1 = args[1].(repository.GetDeploymentsByAppAndStatusesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetDeploymentsByAppAndStatuses_Call) Return(deployments []repository.Deployment, err error) *Queries_GetDeploymentsByAppAndStatuses_Call {
	_c.Call.Return(deployments, err)
	return _c
}

func (_c *Queries_GetDeploymentsByAppAndStatuses_Call) RunAndReturn(run func(ctx context.Context, arg repository.GetDeploymentsByAppAndStatusesParams) ([]repository.Deployment, error)) *Queries_GetDeploymentsByAppAndStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeploymentsNeedingWork provides a mock function for the type Queries
func (_mock *Queries) GetDeploymentsNeedingWork(ctx context.Context) ([]repository.Deployment, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDeploymentsNeedingWork")
	}

	var r0 []repository.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repository.Deployment, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repository.Deployment); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetDeploymentsNeedingWork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeploymentsNeedingWork'
type Queries_GetDeploymentsNeedingWork_Call struct {
	*mock.Call
}

// GetDeploymentsNeedingWork is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queries_Expecter) GetDeploymentsNeedingWork(ctx interface{}) *Queries_GetDeploymentsNeedingWork_Call {
	return &Queries_GetDeploymentsNeedingWork_Call{Call: _e.mock.On("GetDeploymentsNeedingWork", ctx)}
}

func (_c *Queries_GetDeploymentsNeedingWork_Call) Run(run func(ctx context.Context)) *Queries_GetDeploymentsNeedingWork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queries_GetDeploymentsNeedingWork_Call) Return(deployments []repository.Deployment, err error) *Queries_GetDeploymentsNeedingWork_Call {
	_c.Call.Return(deployments, err)
	return _c
}

func (_c *Queries_GetDeploymentsNeedingWork_Call) RunAndReturn(run func(ctx context.Context) ([]repository.Deployment, error)) *Queries_GetDeploymentsNeedingWork_Call {
	_c.Call.Return(run)
	return _c
}

// GetDomain provides a mock function for the type Queries
func (_mock *Queries) GetDomain(ctx context.Context, id string) (repository.Domain, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDomain")
	}

	var r0 repository.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.Domain, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.Domain); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Domain)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDomain'
type Queries_GetDomain_Call struct {
	*mock.Call
}

// GetDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Queries_Expecter) GetDomain(ctx interface{}, id interface{}) *Queries_GetDomain_Call {
	return &Queries_GetDomain_Call{Call: _e.mock.On("GetDomain", ctx, id)}
}

func (_c *Queries_GetDomain_Call) Run(run func(ctx context.Context, id string)) *Queries_GetDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetDomain_Call) Return(domain repository.Domain, err error) *Queries_GetDomain_Call {
	_c.Call.Return(domain, err)
	return _c
}

func (_c *Queries_GetDomain_Call) RunAndReturn(run func(ctx context.Context, id string) (repository.Domain, error)) *Queries_GetDomain_Call {
	_c.Call.Return(run)
	return _c
}

// GetDomainByName provides a mock function for the type Queries
func (_mock *Queries) GetDomainByName(ctx context.Context, domain string) (repository.Domain, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetDomainByName")
	}

	var r0 repository.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.Domain, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.Domain); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		r0 = ret.Get(0).(repository.Domain)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetDomainByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDomainByName'
type Queries_GetDomainByName_Call struct {
	*mock.Call
}

// GetDomainByName is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *Queries_Expecter) GetDomainByName(ctx interface{}, domain interface{}) *Queries_GetDomainByName_Call {
	return &Queries_GetDomainByName_Call{Call: _e.mock.On("GetDomainByName", ctx, domain)}
}

func (_c *Queries_GetDomainByName_Call) Run(run func(ctx context.Context, domain string)) *Queries_GetDomainByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetDomainByName_Call) Return(domain1 repository.Domain, err error) *Queries_GetDomainByName_Call {
	_c.Call.Return(domain1, err)
	return _c
}

func (_c *Queries_GetDomainByName_Call) RunAndReturn(run func(ctx context.Context, domain string) (repository.Domain, error)) *Queries_GetDomainByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentDeploymentLogs provides a mock function for the type Queries
func (_mock *Queries) GetRecentDeploymentLogs(ctx context.Context, arg repository.GetRecentDeploymentLogsParams) ([]repository.DeploymentLog, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentDeploymentLogs")
	}

	var r0 []repository.DeploymentLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.GetRecentDeploymentLogsParams) ([]repository.DeploymentLog, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.GetRecentDeploymentLogsParams) []repository.DeploymentLog); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DeploymentLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.GetRecentDeploymentLogsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetRecentDeploymentLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentDeploymentLogs'
type Queries_GetRecentDeploymentLogs_Call struct {
	*mock.Call
}

// GetRecentDeploymentLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.GetRecentDeploymentLogsParams
func (_e *Queries_Expecter) GetRecentDeploymentLogs(ctx interface{}, arg interface{}) *Queries_GetRecentDeploymentLogs_Call {
	return &Queries_GetRecentDeploymentLogs_Call{Call: _e.mock.On("GetRecentDeploymentLogs", ctx, arg)}
}

func (_c *Queries_GetRecentDeploymentLogs_Call) Run(run func(ctx context.Context, arg repository.GetRecentDeploymentLogsParams)) *Queries_GetRecentDeploymentLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.GetRecentDeploymentLogsParams
		if args[1] != nil {
			arg1 = args[1].(repository.GetRecentDeploymentLogsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetRecentDeploymentLogs_Call) Return(deploymentLogs []repository.DeploymentLog, err error) *Queries_GetRecentDeploymentLogs_Call {
	_c.Call.Return(deploymentLogs, err)
	return _c
}

func (_c *Queries_GetRecentDeploymentLogs_Call) RunAndReturn(run func(ctx context.Context, arg repository.GetRecentDeploymentLogsParams) ([]repository.DeploymentLog, error)) *Queries_GetRecentDeploymentLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaleDeployments provides a mock function for the type Queries
func (_mock *Queries) GetStaleDeployments(ctx context.Context, createdAt time.Time) ([]repository.Deployment, error) {
	ret := _mock.Called(ctx, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for GetStaleDeployments")
	}

	var r0 []repository.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]repository.Deployment, error)); ok {
		return returnFunc(ctx, createdAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []repository.Deployment); ok {
		r0 = returnFunc(ctx, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, createdAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_GetStaleDeployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaleDeployments'
type Queries_GetStaleDeployments_Call struct {
	*mock.Call
}

// GetStaleDeployments is a helper method to define mock.On call
//   - ctx context.Context
//   - createdAt time.Time
func (_e *Queries_Expecter) GetStaleDeployments(ctx interface{}, createdAt interface{}) *Queries_GetStaleDeployments_Call {
	return &Queries_GetStaleDeployments_Call{Call: _e.mock.On("GetStaleDeployments", ctx, createdAt)}
}

func (_c *Queries_GetStaleDeployments_Call) Run(run func(ctx context.Context, createdAt time.Time)) *Queries_GetStaleDeployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_GetStaleDeployments_Call) Return(deployments []repository.Deployment, err error) *Queries_GetStaleDeployments_Call {
	_c.Call.Return(deployments, err)
	return _c
}

func (_c *Queries_GetStaleDeployments_Call) RunAndReturn(run func(ctx context.Context, createdAt time.Time) ([]repository.Deployment, error)) *Queries_GetStaleDeployments_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllDomains provides a mock function for the type Queries
func (_mock *Queries) ListAllDomains(ctx context.Context) ([]repository.Domain, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllDomains")
	}

	var r0 []repository.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repository.Domain, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repository.Domain); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Domain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_ListAllDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllDomains'
type Queries_ListAllDomains_Call struct {
	*mock.Call
}

// ListAllDomains is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queries_Expecter) ListAllDomains(ctx interface{}) *Queries_ListAllDomains_Call {
	return &Queries_ListAllDomains_Call{Call: _e.mock.On("ListAllDomains", ctx)}
}

func (_c *Queries_ListAllDomains_Call) Run(run func(ctx context.Context)) *Queries_ListAllDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queries_ListAllDomains_Call) Return(domains []repository.Domain, err error) *Queries_ListAllDomains_Call {
	_c.Call.Return(domains, err)
	return _c
}

func (_c *Queries_ListAllDomains_Call) RunAndReturn(run func(ctx context.Context) ([]repository.Domain, error)) *Queries_ListAllDomains_Call {
	_c.Call.Return(run)
	return _c
}

// ListApps provides a mock function for the type Queries
func (_mock *Queries) ListApps(ctx context.Context) ([]repository.App, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListApps")
	}

	var r0 []repository.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repository.App, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repository.App); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_ListApps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApps'
type Queries_ListApps_Call struct {
	*mock.Call
}

// ListApps is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queries_Expecter) ListApps(ctx interface{}) *Queries_ListApps_Call {
	return &Queries_ListApps_Call{Call: _e.mock.On("ListApps", ctx)}
}

func (_c *Queries_ListApps_Call) Run(run func(ctx context.Context)) *Queries_ListApps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queries_ListApps_Call) Return(apps []repository.App, err error) *Queries_ListApps_Call {
	_c.Call.Return(apps, err)
	return _c
}

func (_c *Queries_ListApps_Call) RunAndReturn(run func(ctx context.Context) ([]repository.App, error)) *Queries_ListApps_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeploymentsByApp provides a mock function for the type Queries
func (_mock *Queries) ListDeploymentsByApp(ctx context.Context, appID string) ([]repository.Deployment, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for ListDeploymentsByApp")
	}

	var r0 []repository.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]repository.Deployment, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []repository.Deployment); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_ListDeploymentsByApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeploymentsByApp'
type Queries_ListDeploymentsByApp_Call struct {
	*mock.Call
}

// ListDeploymentsByApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *Queries_Expecter) ListDeploymentsByApp(ctx interface{}, appID interface{}) *Queries_ListDeploymentsByApp_Call {
	return &Queries_ListDeploymentsByApp_Call{Call: _e.mock.On("ListDeploymentsByApp", ctx, appID)}
}

func (_c *Queries_ListDeploymentsByApp_Call) Run(run func(ctx context.Context, appID string)) *Queries_ListDeploymentsByApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_ListDeploymentsByApp_Call) Return(deployments []repository.Deployment, err error) *Queries_ListDeploymentsByApp_Call {
	_c.Call.Return(deployments, err)
	return _c
}

func (_c *Queries_ListDeploymentsByApp_Call) RunAndReturn(run func(ctx context.Context, appID string) ([]repository.Deployment, error)) *Queries_ListDeploymentsByApp_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeploymentsByStatus provides a mock function for the type Queries
func (_mock *Queries) ListDeploymentsByStatus(ctx context.Context, status string) ([]repository.Deployment, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for ListDeploymentsByStatus")
	}

	var r0 []repository.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]repository.Deployment, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []repository.Deployment); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_ListDeploymentsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeploymentsByStatus'
type Queries_ListDeploymentsByStatus_Call struct {
	*mock.Call
}

// ListDeploymentsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *Queries_Expecter) ListDeploymentsByStatus(ctx interface{}, status interface{}) *Queries_ListDeploymentsByStatus_Call {
	return &Queries_ListDeploymentsByStatus_Call{Call: _e.mock.On("ListDeploymentsByStatus", ctx, status)}
}

func (_c *Queries_ListDeploymentsByStatus_Call) Run(run func(ctx context.Context, status string)) *Queries_ListDeploymentsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_ListDeploymentsByStatus_Call) Return(deployments []repository.Deployment, err error) *Queries_ListDeploymentsByStatus_Call {
	_c.Call.Return(deployments, err)
	return _c
}

func (_c *Queries_ListDeploymentsByStatus_Call) RunAndReturn(run func(ctx context.Context, status string) ([]repository.Deployment, error)) *Queries_ListDeploymentsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListDomainsByApp provides a mock function for the type Queries
func (_mock *Queries) ListDomainsByApp(ctx context.Context, appID string) ([]repository.Domain, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for ListDomainsByApp")
	}

	var r0 []repository.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]repository.Domain, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []repository.Domain); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Domain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queries_ListDomainsByApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDomainsByApp'
type Queries_ListDomainsByApp_Call struct {
	*mock.Call
}

// ListDomainsByApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *Queries_Expecter) ListDomainsByApp(ctx interface{}, appID interface{}) *Queries_ListDomainsByApp_Call {
	return &Queries_ListDomainsByApp_Call{Call: _e.mock.On("ListDomainsByApp", ctx, appID)}
}

func (_c *Queries_ListDomainsByApp_Call) Run(run func(ctx context.Context, appID string)) *Queries_ListDomainsByApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_ListDomainsByApp_Call) Return(domains []repository.Domain, err error) *Queries_ListDomainsByApp_Call {
	_c.Call.Return(domains, err)
	return _c
}

func (_c *Queries_ListDomainsByApp_Call) RunAndReturn(run func(ctx context.Context, appID string) ([]repository.Domain, error)) *Queries_ListDomainsByApp_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApp provides a mock function for the type Queries
func (_mock *Queries) UpdateApp(ctx context.Context, arg repository.UpdateAppParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.UpdateAppParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_UpdateApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApp'
type Queries_UpdateApp_Call struct {
	*mock.Call
}

// UpdateApp is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.UpdateAppParams
func (_e *Queries_Expecter) UpdateApp(ctx interface{}, arg interface{}) *Queries_UpdateApp_Call {
	return &Queries_UpdateApp_Call{Call: _e.mock.On("UpdateApp", ctx, arg)}
}

func (_c *Queries_UpdateApp_Call) Run(run func(ctx context.Context, arg repository.UpdateAppParams)) *Queries_UpdateApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.UpdateAppParams
		if args[1] != nil {
			arg1 = args[1].(repository.UpdateAppParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_UpdateApp_Call) Return(err error) *Queries_UpdateApp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_UpdateApp_Call) RunAndReturn(run func(ctx context.Context, arg repository.UpdateAppParams) error) *Queries_UpdateApp_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeploymentStatus provides a mock function for the type Queries
func (_mock *Queries) UpdateDeploymentStatus(ctx context.Context, arg repository.UpdateDeploymentStatusParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeploymentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.UpdateDeploymentStatusParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_UpdateDeploymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeploymentStatus'
type Queries_UpdateDeploymentStatus_Call struct {
	*mock.Call
}

// UpdateDeploymentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.UpdateDeploymentStatusParams
func (_e *Queries_Expecter) UpdateDeploymentStatus(ctx interface{}, arg interface{}) *Queries_UpdateDeploymentStatus_Call {
	return &Queries_UpdateDeploymentStatus_Call{Call: _e.mock.On("UpdateDeploymentStatus", ctx, arg)}
}

func (_c *Queries_UpdateDeploymentStatus_Call) Run(run func(ctx context.Context, arg repository.UpdateDeploymentStatusParams)) *Queries_UpdateDeploymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.UpdateDeploymentStatusParams
		if args[1] != nil {
			arg1 = args[1].(repository.UpdateDeploymentStatusParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_UpdateDeploymentStatus_Call) Return(err error) *Queries_UpdateDeploymentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_UpdateDeploymentStatus_Call) RunAndReturn(run func(ctx context.Context, arg repository.UpdateDeploymentStatusParams) error) *Queries_UpdateDeploymentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeploymentStatusWithActivatedAt provides a mock function for the type Queries
func (_mock *Queries) UpdateDeploymentStatusWithActivatedAt(ctx context.Context, arg repository.UpdateDeploymentStatusWithActivatedAtParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeploymentStatusWithActivatedAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.UpdateDeploymentStatusWithActivatedAtParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_UpdateDeploymentStatusWithActivatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeploymentStatusWithActivatedAt'
type Queries_UpdateDeploymentStatusWithActivatedAt_Call struct {
	*mock.Call
}

// UpdateDeploymentStatusWithActivatedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.UpdateDeploymentStatusWithActivatedAtParams
func (_e *Queries_Expecter) UpdateDeploymentStatusWithActivatedAt(ctx interface{}, arg interface{}) *Queries_UpdateDeploymentStatusWithActivatedAt_Call {
	return &Queries_UpdateDeploymentStatusWithActivatedAt_Call{Call: _e.mock.On("UpdateDeploymentStatusWithActivatedAt", ctx, arg)}
}

func (_c *Queries_UpdateDeploymentStatusWithActivatedAt_Call) Run(run func(ctx context.Context, arg repository.UpdateDeploymentStatusWithActivatedAtParams)) *Queries_UpdateDeploymentStatusWithActivatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.UpdateDeploymentStatusWithActivatedAtParams
		if args[1] != nil {
			arg1 = args[1].(repository.UpdateDeploymentStatusWithActivatedAtParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_UpdateDeploymentStatusWithActivatedAt_Call) Return(err error) *Queries_UpdateDeploymentStatusWithActivatedAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_UpdateDeploymentStatusWithActivatedAt_Call) RunAndReturn(run func(ctx context.Context, arg repository.UpdateDeploymentStatusWithActivatedAtParams) error) *Queries_UpdateDeploymentStatusWithActivatedAt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeploymentStatusWithStoppedAt provides a mock function for the type Queries
func (_mock *Queries) UpdateDeploymentStatusWithStoppedAt(ctx context.Context, arg repository.UpdateDeploymentStatusWithStoppedAtParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeploymentStatusWithStoppedAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.UpdateDeploymentStatusWithStoppedAtParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_UpdateDeploymentStatusWithStoppedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeploymentStatusWithStoppedAt'
type Queries_UpdateDeploymentStatusWithStoppedAt_Call struct {
	*mock.Call
}

// UpdateDeploymentStatusWithStoppedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.UpdateDeploymentStatusWithStoppedAtParams
func (_e *Queries_Expecter) UpdateDeploymentStatusWithStoppedAt(ctx interface{}, arg interface{}) *Queries_UpdateDeploymentStatusWithStoppedAt_Call {
	return &Queries_UpdateDeploymentStatusWithStoppedAt_Call{Call: _e.mock.On("UpdateDeploymentStatusWithStoppedAt", ctx, arg)}
}

func (_c *Queries_UpdateDeploymentStatusWithStoppedAt_Call) Run(run func(ctx context.Context, arg repository.UpdateDeploymentStatusWithStoppedAtParams)) *Queries_UpdateDeploymentStatusWithStoppedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.UpdateDeploymentStatusWithStoppedAtParams
		if args[1] != nil {
			arg1 = args[1].(repository.UpdateDeploymentStatusWithStoppedAtParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_UpdateDeploymentStatusWithStoppedAt_Call) Return(err error) *Queries_UpdateDeploymentStatusWithStoppedAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_UpdateDeploymentStatusWithStoppedAt_Call) RunAndReturn(run func(ctx context.Context, arg repository.UpdateDeploymentStatusWithStoppedAtParams) error) *Queries_UpdateDeploymentStatusWithStoppedAt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDomain provides a mock function for the type Queries
func (_mock *Queries) UpdateDomain(ctx context.Context, arg repository.UpdateDomainParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.UpdateDomainParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queries_UpdateDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDomain'
type Queries_UpdateDomain_Call struct {
	*mock.Call
}

// UpdateDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.UpdateDomainParams
func (_e *Queries_Expecter) UpdateDomain(ctx interface{}, arg interface{}) *Queries_UpdateDomain_Call {
	return &Queries_UpdateDomain_Call{Call: _e.mock.On("UpdateDomain", ctx, arg)}
}

func (_c *Queries_UpdateDomain_Call) Run(run func(ctx context.Context, arg repository.UpdateDomainParams)) *Queries_UpdateDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.UpdateDomainParams
		if args[1] != nil {
			arg1 = args[1].(repository.UpdateDomainParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queries_UpdateDomain_Call) Return(err error) *Queries_UpdateDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queries_UpdateDomain_Call) RunAndReturn(run func(ctx context.Context, arg repository.UpdateDomainParams) error) *Queries_UpdateDomain_Call {
	_c.Call.Return(run)
	return _c
}
